language: node_js
node_js:
- '7.2'
beforescript:
- npm install -g gulp
- npm install
script: gulp package-app
deploy:
  provider: heroku
  app: myApp
  api_key:
    secure: AvqA7u8g9fy1EsNmS9Faq0W046fvHFX0FbxlaZ+QpYDEOTvDXCjs4HEVIDbTnqA1XgugTftrXeUC442nLtuFtwkHNS6mv7zdjZ5qHNQRmBd//m6Zl3hnZ+HtwfMJnCukQ+AF2kWbQT5CfbIgWIdSqUfjecOXLBXWqeSh+3Pq2pzAvs76Idkqga798zOHS93qXlc2unzMDjtoHiNRXgPfunNAaw6cYREah14NUcCl1sZn91yvuUSSKLYoexL0eM6BGSItoT4Eh16VO/fs+VMD564VQYCR7+BLwng1UQbxWxAj6uGgqXKrQd0Ld3iU0BWCCBjA0CHtNYc932UCnTHDQT9IbNo4GlYsboQrPvXJW6qYvU1tIeSRFWaTtI6/CRAlp8sDEuEVZp7uDbVcdd40F0K/0Zk6xePkSXCVXXXFDE8vnITQb9mDLKQecAIbWYMiDpg2XKgByDCv+sDIUvd2bo2JsDNYcnf9an8Tjurfa3ST6jIVw3tGvFhl5b1+Trd+bdAMlPSow2z89S/8BNj7dMqtz3VW5peSRcrFA/1d2DzS2qa+3o3sgP+5KiSSzh8R0sYByu1Q77jYRXK5mvistL6EolsbomBYh8nB+1t9QTuOIxLQcIoyvExLGR87AFepvplBNwjL82w+cYdwEd72pYAzfweDO+mLQLtwKl3btO8=
